### ISSUE TITLE
global log request response middleware

### ISSUE THREAD

**Issue by warkop** [RegiAdi/hatchet#8]
Looks like there is no global log, can I implement that on this repo?

**Comment by RegiAdi** [comment]
Can you explain the details about global log that you want to implement?

**Comment by warkop** [comment]
If any request/call API is coming, the apps will write a log contain the request from client and response from the apps backend. The log will showing onto console. There is example what it looks like:

`{"level":"INFO","time":"2021-12-15T15:17:27.121+0700","message":"HTTP SERVER RUNNING ON PORT 8000","uuid":"3ed23e7f-b509-424b-81d1-8eaf86769f0e","uri":"/ping","error_code":"","request_param":"","response_message":"Server Running on Port 8000","request_time":"2021-12-15 15:17:27.121686 +0700 +07 m=+0.003689201","response_time":"2021-12-15 15:17:27.1217694 +0700 +07 m=+0.003772601","processing_time":"0ms","package":"main","handler":"main","file":"main.go","line":25}`

**Comment by RegiAdi** [comment]
is it only logged to console? or saved into file?

**Comment by warkop** [comment]
only logged to console, since log into file is not recommended because if something wrong with our VM or cluster there are potentially got lose all logs. We can collect the log using Logstash or Loki later, the agent will saved the log to the other place

**Comment by RegiAdi** [comment]
Okay that's good, you can implement that. Thanks for the idea.

**Comment by warkop** [comment]
Your welcome, you can close this issue, thank you for the discussion
