### ISSUE TITLE
feature flag

### ISSUE THREAD

**Issue by warkop** [RegiAdi/hatchet#9]
Hey, can we implementing feature flagging?

I can implement it but we need change some authorization token, I suggest to using JWT token, we can insert the role user, so we can add condition for our flagging want to be

ref: https://github.com/thomaspoignant/go-feature-flag

**Comment by RegiAdi** [comment]
Can you implement auth using JWT on separate middleware? so we can toggle or set it up from env, or from feature flagging

for example:
1. API Token based (API Token saved on db)
2. JWT Token based

**Comment by warkop** [comment]
I can, but we need add the role parameter on saving user API, so we can save the role for feature flagging purpose

**Comment by RegiAdi** [comment]
Okay, that would be great.

**Comment by warkop** [comment]
Alright, you can close this issue, thank you for discussing
